# Generated by Django 4.0.6 on 2022-08-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='CATEGORY',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mk', 'Kurta'), ('msh', 'Sherwani'), ('ms', 'suit'), ('wk', 'kurti'), ('wsa', 'Saree'), ('wsu', 'Suit'), ('kb', 'Boys'), ('kg', 'Girls'), ('br', 'brooch'), ('ml', 'mala'), ('jt', 'juti'), ('sf', 'safa'), ('kp', 'kamarpatta'), ('jw', 'jwellery'), ('er', 'earrings')], default='', max_length=5),
            preserve_default=False,
        ),
    ]
